CREATE OR REPLACE VIEW BUSINESS_DATE AS
SELECT TRUNC ( SYSDATE) - (LEVEL - 1) BUSINESS_DATE
FROM DUAL
CONNECT BY LEVEL < TRUNC ( SYSDATE) - ADD_MONTHS ( TRUNC ( SYSDATE), -48)
UNION ALL
SELECT TRUNC ( SYSDATE) + LEVEL BUSINESS_DATE
FROM DUAL
CONNECT BY LEVEL < TRUNC ( SYSDATE) - ADD_MONTHS ( TRUNC ( SYSDATE), -24)
